### ISSUE TITLE
Webhooks are not always triggered

### ISSUE THREAD

**Issue by mateusz-domanski** [umbraco/Umbraco.Heartcore.Issues#157]
### Summary

Webhooks behaviour is inconsistent, often `unpublish` and `publish `events are not triggered when content is transferred between environments.

### Steps to reproduce

Unpublish scenario:
1. Unpublish the content item (with language variants enabled) in lower environment, eg. Staging.
2. Transfer the item to the next environment, eg. Live, using Umbraco Deploy.
3. The content item is marked as unpublished.
4. No webhooks were triggered.

Publish scenario:
1. Publish the content item (with language variants enabled) in lower environment, eg. Staging.
2. Transfer the item to the next environment, eg. Live, using Umbraco Deploy.
3. The content item is marked as published.
4. No webhooks were triggered.

### Expected result

I expect to receive `unpublished` /`published` webhook event and see that it was triggered in the Webhooks Deliveries dashboard.

### Actual result

Content item was marked as unpublished/published but no webhooks were triggered.

**Comment by jmf-umbraco** [comment]
Hi @mateusz-domanski,

Thanks for the report!

The core CMS only recently made it possible to resolve this issue. We released a change on Wedesday this week that incorporated a fix. I've tested your scenarios above and it no longer looks possible to reproduce - i.e. correct hooks seem to be firing. Can you please re-test and confirm?

**Comment by mateusz-domanski** [comment]
Hi @jmf-umbraco,

That's great news!
We haven't seen any new occurences of this issue in recent days, but I think we need 2-3 more days to be sure that the issue is gone.

Thanks!

**Comment by mateusz-domanski** [comment]
Hi @jmf-umbraco,

Unfortunately, it looks that the issue still exists, both for publishing and unpublishing, when transferring the content.

One of the scenarios:
1. Create a ListView document type.
2. Create a child document type.
3. Publish some content (the list view with a few child elements) in a lower environment
4. Queue for transfer (with the `Include all items below` option selected)
5. Transfer to next environment
6. Webhooks are not triggered for all child items.

**Comment by jmf-umbraco** [comment]
Sorry to hear that.

Can you please clarify if this is for all publishes/unpublishes following the instructions above, or does it only occur sometimes? Are there any errors in the Umbraco log (viewable from the Settings tab) on the destination environment at the time of transfer?

We'll take another look and see if we can spot what's going wrong.

**Comment by mateusz-domanski** [comment]
For the ListView scenario I think this happense every time but number of webhooks fired is different.
On Wednesday, I created a list with 12 items in Dev environment. Then I transferred it to Staging env and Staging triggered webhooks for 4 child items only (so webhooks for 8 child items and the parent item were missing). To fix this, I published the list with all descendants again, manually, in Staging. Then when I transfered it to Live env, again not all webhooks were triggered but Live triggered them for a few more child items.
Usually when webhook is not triggered we don't see any error logs. But in this case I found some mapping errors. Not sure if it's related.
![Image](https://github.com/user-attachments/assets/b63e4d51-f6f0-4eed-9c52-341c53dc3b8c)
And later the following warning
![Image](https://github.com/user-attachments/assets/e1f656ce-785c-4a75-9cfc-9fd49eb9c5fa)

**Comment by mateusz-domanski** [comment]
Also I'd like to share one more scenario - transferring two unpublished content items (with langugae variants enabled):
1. Content Editor scheduled the transfer of two documents from Staging environment to Live environment:
- `IT – Image – Trenitalia Code`
- `IT_Trenitalia`

2. In the logs we can see that these two documents were unpublished (no errors)

Live:
![Image](https://github.com/user-attachments/assets/99b87965-8f2f-427a-bd56-750ccb1e9c71)

Staging:
![Image](https://github.com/user-attachments/assets/a209c51f-5bde-4470-bc7c-db8108948c02)

3. Both documents were marked as unpublished in the content tree, we can see that below for one of the documents
![Image](https://github.com/user-attachments/assets/94575b84-38f2-465f-97d0-e6cbd38dbee8)

4. Only one contentUnpublished webhook event was triggered which is not correct. We expected two events
![Image](https://github.com/user-attachments/assets/faf526a0-0c4c-438a-95bb-79aa5d9c3cbd)

**Comment by jmf-umbraco** [comment]
Thanks for the info. We're continuing to investigate this week.

**Comment by jmf-umbraco** [comment]
Hi all,

Sorry for radio silence on this one for a while.

We've identified the cause(s) of this and have a fix that will be rolled out tomorrow.
